[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc = "0.8.19"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mumbai = "https://polygon-mumbai.blockpi.network/v1/rpc/public"
local = "http://127.0.0.1:8545"

[etherscan]
mumbai-api-key = { key = "${MUMBAI_API_KEY}" }


